baseURL = 'https://dypnet.no/'
languageCode = 'no-nb'
title = 'Dypnet'
theme = 'dypnet'

[menu]
  [[menu.main]]
    identifier = "om"
    name = "Om"
    url = "/om"
    weight = 10

  [[menu.main]]
    identifier = "leika"
    name = "Bjorlileikane"
    url = "/bjorlileikane"
    weight = 20

